# Generated by Django 5.1.4 on 2025-01-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uservisits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisit',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_visits/'),
        ),
    ]
