# Generated by Django 5.1.4 on 2025-01-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='badges/')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('VISIT_COUNT', 'Visit Count'), ('SPECIFIC_PLACE', 'Specific Place'), ('CATEGORY', 'Category'), ('EVENT', 'Event'), ('COUNTRY', 'Country'), ('CITY', 'City')], max_length=20)),
                ('target_value', models.PositiveIntegerField(blank=True, null=True)),
                ('target_category', models.CharField(blank=True, max_length=50, null=True)),
                ('target_country', models.CharField(blank=True, max_length=50, null=True)),
                ('target_city', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
