# Generated by Django 5.0.4 on 2025-01-02 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.badge'),
        ),
        migrations.AddField(
            model_name='mission',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place'),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='type',
            field=models.CharField(choices=[('VISIT_COUNT', 'Visit Count'), ('SPECIFIC_PLACE', 'Specific Place'), ('CATEGORY', 'Category'), ('EVENT', 'Event'), ('COUNTRY', 'Country'), ('CITY', 'City')], default='basic', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
