# Generated by Django 5.0.4 on 2025-01-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
